export type UserVO = {
    id: string,
    nickName: string,
    avatar: string,
    sex: number,
    userRole: string,
    personIntroduction: string,
    noticeInfo: string,
    birthday: string,
    school: boolean,
    expireAt: number,
    token: string,
    fansCount: number,
    focusCount: number,
    likeCount: number,
    playCount: number,
    haveFocus: boolean,
    theme: number,
    currentCoinCount: number
}